branch-defaults:
  main:
    environment: Amazon-ads-optimizer-env
global:
  application_name: amazon-ads-optimizer
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: git
  workspace_type: Application
